version: 2

jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:12
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-dirs
      - run: npm ci
      - save_cache:
          key: cache-dirs
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: junit-results
      # - run:
      #     name: Running E2E tests with multiple reporters
      #     command: npm run test-multiple
      # - store_test_results:
      #     path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  commit:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
